### ISSUE TITLE
Bring up code up to a newer version and make test pass 

### ISSUE THREAD

**Issue by andrewshatnyy** [alextsui05/paperclip-backblaze#1]
Needs
* tests to pass
* docker file for deploys
* ci
* rubocop
* newer version of ruby

**Comment by alextsui05** [comment]
@andrewshatnyy Thanks for opening up this issue. Those are all pretty fundamental for supporting a gem, so I'm going to spend some time getting this set up.

As an aside, Rails 5.2 (beta as of this comment) is introducing ActiveStorage, which will be core support for what paperclip does. In parallel with sprucing up this paperclip gem, I'm planning to set up a gem that will add Backblaze support for ActiveStorage.

**Comment by andrewshatnyy** [comment]
Perfect. This gem can be split up into two Backblaze and the BackblazeStorage as well. I trust that is  important to keep in mind people who use Sinatra and not only the Rails.
I've created a PR for this issue https://github.com/alextsui05/paperclip-backblaze/pull/2 so you don't have to set those up yourself.

Cheers for your work on this gem.

**Comment by hovancik** [comment]
Awesome, is there a link to active storage gem, yet?

**Comment by alextsui05** [comment]
@hovancik Hi, I haven't made progress with it yet. 

The problem right now is that this gem and the new active storage gem will depend on common code in the `backblaze` gem, which isn't being updated. I need to extract this common code, backport updates to it, and then reference it from this and the active storage gem.

I probably won't get to this until next month at this rate, but just to give you an update, that's the plan.

**Comment by andrewshatnyy** [comment]
@hovancik for now just use the github reference it works fine.
@alextsui05 please close this issue as you've merged the PR already.

**Comment by hovancik** [comment]
There is also https://github.com/fog/fog-backblaze that doesn't seems to use any gem.

**Comment by alextsui05** [comment]
@hovancik Thanks, that gem looks like a good reference. I'll have a look at how they make it work.
